import { precacheAndRoute } from 'workbox-precaching';

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ─── LIFECYCLE: Immediate takeover ─────────────────────────────────────────
self.addEventListener('install', (event) => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(clients.claim());
});

// ─── PUSH: Handle incoming background push notifications ───────────────────
// This fires regardless of whether the app is open or closed.
// The OS/browser wakes the SW, runs this handler, then goes back to sleep.
self.addEventListener('push', function (event) {
    if (!event.data) return;
    
    let data = {};
    try {
        data = event.data.json();
    } catch (e) {
        data = { title: 'New Alert', body: event.data.text() };
    }
    
    const options = {
        body: data.body || 'New admin activity detected.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [500, 110, 500, 110, 450, 110, 200, 110, 170, 40, 450, 110, 200, 110],
        tag: `admin-alert-${Date.now()}`, // Unique tag = fresh vibration/sound every time
        renotify: true,
        requireInteraction: true, // Keeps notification on screen until admin acts
        silent: false,
        data: {
            dateOfArrival: Date.now(),
            url: data.url || '/admin/leads'
        }
    };

    event.waitUntil(
        self.registration.showNotification(data.title || 'Executive Alert', options)
    );
});

// ─── SUBSCRIPTION CHANGE: Auto-renew when browser rotates the push key ──────
// This is the CRITICAL missing piece. When Chrome/Android rotates a subscription
// (after a SW update, or periodically), this event fires. We MUST re-register
// with the backend or all future pushes go to a dead endpoint.
self.addEventListener('pushsubscriptionchange', function (event) {
    event.waitUntil(
        self.registration.pushManager.getSubscription()
            .then(async (subscription) => {
                if (!subscription) return;
                
                // Re-register the new/current subscription with the backend
                await fetch('/api/notifications/subscribe', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(subscription)
                });
            })
            .catch(err => console.error('[SW] pushsubscriptionchange error:', err))
    );
});

// ─── MESSAGE: Handle commands from the main page ────────────────────────────
self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'FLUSH_PENDING_NOTIFICATIONS') {
        // Called by main.js when internet comes back online
        event.waitUntil(flushPendingNotifications());
    }
});

// ─── ONLINE: Flush pending notifications when network is restored ───────────
// This catches the case where the device was offline while notifications
// were sent — when internet comes back, we fetch and show all missed alerts.
self.addEventListener('fetch', function (event) {
    // Only intercept our special reconnect check
    return;
});

async function flushPendingNotifications() {
    try {
        const response = await fetch('/api/notifications/pending');
        if (!response.ok) return;
        
        const { notifications } = await response.json();
        if (!notifications || notifications.length === 0) return;
        
        // Show each missed notification
        for (const notification of notifications) {
            await self.registration.showNotification(notification.title, {
                body: notification.body,
                icon: '/pwa-192x192.png',
                badge: '/pwa-192x192.png',
                vibrate: [500, 110, 500],
                tag: `admin-missed-${notification._id}`,
                renotify: true,
                data: { url: notification.url || '/admin/leads' }
            });
            
            // Small delay between notifications to avoid OS spam-filtering
            await new Promise(resolve => setTimeout(resolve, 500));
        }
    } catch (err) {
        console.error('[SW] Failed to flush pending notifications:', err);
    }
}

// ─── NOTIFICATION CLICK: Open or focus the admin panel ─────────────────────
self.addEventListener('notificationclick', function (event) {
    event.notification.close();
    
    const targetUrl = event.notification.data?.url || '/admin/leads';
    const fullUrl = new URL(targetUrl, self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
            // Focus existing admin window if open
            for (const client of windowClients) {
                if (client.url.includes('/admin') && 'focus' in client) {
                    client.navigate(fullUrl);
                    return client.focus();
                }
            }
            // Otherwise open a new admin window
            if (clients.openWindow) {
                return clients.openWindow(targetUrl);
            }
        })
    );
});
