import { precacheAndRoute } from 'workbox-precaching';

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ─── LIFECYCLE: Immediate takeover ─────────────────────────────────────────
self.addEventListener('install', (event) => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(clients.claim());
});

// ─── INDEXEDDB AUTH CHECK: Only show notifications if Admin is logged in ──────
function checkIsAdmin() {
    return new Promise((resolve) => {
        const request = indexedDB.open('AdminStore', 1);
        request.onupgradeneeded = (e) => e.target.result.createObjectStore('auth');
        request.onsuccess = (e) => {
            const db = e.target.result;
            if (!db.objectStoreNames.contains('auth')) return resolve(false);
            const tx = db.transaction('auth', 'readonly');
            const getReq = tx.objectStore('auth').get('isAdmin');
            getReq.onsuccess = () => resolve(!!getReq.result);
            getReq.onerror = () => resolve(false);
        };
        request.onerror = () => resolve(false);
    });
}

// ─── PUSH: Handle incoming background push notifications ───────────────────
self.addEventListener('push', function (event) {
    if (!event.data) return;

    event.waitUntil(
        (async () => {
            // Fulfill user architecture: Check IndexedDB. Only admins get notifications.
            const isAdmin = await checkIsAdmin();
            if (!isAdmin) {
                console.log('[SW] Push received but user is not admin. Ignoring.');
                return;
            }
    
    let data = {};
    try {
        data = event.data.json();
    } catch (e) {
        data = { title: 'New Alert', body: event.data.text() };
    }
    
    const options = {
        body: data.body || 'New admin activity detected.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [500, 110, 500, 110, 450, 110, 200, 110, 170, 40, 450, 110, 200, 110],
        tag: `admin-alert-${Date.now()}`, // Unique tag = fresh vibration/sound every time
        renotify: true,
        requireInteraction: true, // Keeps notification on screen until admin acts
        silent: false,
        data: {
            dateOfArrival: Date.now(),
            url: data.url || '/admin/leads'
        }
    };

        await self.registration.showNotification(data.title || 'Executive Alert', options);
        })()
    );
});

// ─── SUBSCRIPTION CHANGE: Auto-renew when browser rotates the push key ──────
// This is the CRITICAL missing piece. When Chrome/Android rotates a subscription
// (after a SW update, or periodically), this event fires. We MUST re-register
// with the backend or all future pushes go to a dead endpoint.
self.addEventListener('pushsubscriptionchange', function (event) {
    event.waitUntil(
        self.registration.pushManager.getSubscription()
            .then(async (subscription) => {
                if (!subscription) return;
                
                // Re-register the new/current subscription with the backend
                const apiUrl = self.location.origin.includes('5173') ? 'http://localhost:5000' : self.location.origin;
                await fetch(`${apiUrl}/api/notifications/subscribe`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(subscription)
                });
            })
            .catch(err => console.error('[SW] pushsubscriptionchange error:', err))
    );
});

// ─── MESSAGE: Handle commands from the main page ────────────────────────────
self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'FLUSH_PENDING_NOTIFICATIONS') {
        // Called by main.js when internet comes back online
        event.waitUntil(flushPendingNotifications());
    }
});

// ─── BACKGROUND SYNC: Flush pending when device restores internet (App closed)
self.addEventListener('sync', function(event) {
    if (event.tag === 'flush-notifications') {
        event.waitUntil(flushPendingNotifications());
    }
});

self.addEventListener('fetch', function (event) {
    return;
});

async function flushPendingNotifications() {
    try {
        const isAdmin = await checkIsAdmin();
        if (!isAdmin) return;

        const apiUrl = self.location.origin.includes('5173') ? 'http://localhost:5000' : self.location.origin;
        const response = await fetch(`${apiUrl}/api/notifications/pending`);
        if (!response.ok) return;
        
        const { notifications } = await response.json();
        if (!notifications || notifications.length === 0) return;
        
        // Show each missed notification
        for (const notification of notifications) {
            await self.registration.showNotification(notification.title, {
                body: notification.body,
                icon: '/pwa-192x192.png',
                badge: '/pwa-192x192.png',
                vibrate: [500, 110, 500],
                tag: `admin-missed-${notification._id}`,
                renotify: true,
                data: { url: notification.url || '/admin/leads' }
            });
            
            // Small delay between notifications to avoid OS spam-filtering
            await new Promise(resolve => setTimeout(resolve, 500));
        }
    } catch (err) {
        console.error('[SW] Failed to flush pending notifications:', err);
    }
}

// ─── NOTIFICATION CLICK: Open or focus the admin panel ─────────────────────
self.addEventListener('notificationclick', function (event) {
    event.notification.close();
    
    const targetUrl = event.notification.data?.url || '/admin/leads';
    const fullUrl = new URL(targetUrl, self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
            // Focus existing admin window if open
            for (const client of windowClients) {
                if (client.url.includes('/admin') && 'focus' in client) {
                    client.navigate(fullUrl);
                    return client.focus();
                }
            }
            // Otherwise open a new admin window
            if (clients.openWindow) {
                return clients.openWindow(targetUrl);
            }
        })
    );
});
