import { precacheAndRoute } from 'workbox-precaching';

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', () => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(clients.claim());
});

// Handle Push Notifications
self.addEventListener('push', function (event) {
    if (!event.data) return;
    
    let data = {};
    try {
        data = event.data.json();
    } catch (e) {
        data = { title: 'Executive Alert', body: event.data.text() };
    }
    
    const options = {
        body: data.body || 'New ecosystem activity detected.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [200, 100, 200, 100, 400],
        tag: 'admin-notification', // Consistent tag for high-priority alerts
        renotify: true, // Always vibrate/sound even if same tag
        requireInteraction: true, // Stay until user acts
        data: {
            dateOfArrival: Date.now(),
            url: data.url || '/admin/leads'
        }
    };

    event.waitUntil(
        self.registration.showNotification(data.title || 'Executive Alert', options)
    );
});

// Handle notification click
self.addEventListener('notificationclick', function (event) {
    event.notification.close();
    
    const targetUrl = event.notification.data?.url || '/admin/leads';
    const fullUrl = new URL(targetUrl, self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
            // Check if there is already a window open with this URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === fullUrl && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, open a new window
            if (clients.openWindow) {
                return clients.openWindow(targetUrl);
            }
        })
    );
});
